# Generated by Django 4.2.20 on 2025-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_image_alter_productimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
